# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 368a0b271f0e1b0478e69f58e3e441f4143747a86ba7e54ccba80f73a378ed548c6a55d11a860da04cf3659271e3f4399dd1011c00b725d026eaca8767033de3

test:
  secret_key_base: dfa9bf92ce09e05e59ebef17518d8b01ded06affbca20838bad24b4cc85f74023d1d53a5c5e0ca72eb282874edabfa79ca2b15389e890d0033986ceee7bc14f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
